name = "BangBang"
uuid = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.3.2-DEV"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Future = "9fa8497b-333b-5362-9e8d-4d0656e87820"
InitialValues = "22cec73e-a1b8-11e9-2c92-598750a2cf9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
InitialValues = "â‰¥ 0.2"
julia = "1.0"

[extras]
IRTest = "c9680f28-2a59-47f6-98e4-d41620d42cd2"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["StaticArrays", "Test", "IRTest"]
