name = "BangBang"
uuid = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.3.32-DEV"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Future = "9fa8497b-333b-5362-9e8d-4d0656e87820"
InitialValues = "22cec73e-a1b8-11e9-2c92-598750a2cf9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
Compat = "2.0, 3.0"
ConstructionBase = "0.1, 1.0"
InitialValues = "0.2.4"
Requires = "0.5, 1.0"
Setfield = "0.5.1, 0.6, 0.7, 0.8"
Tables = "0.2, 1.0"
ZygoteRules = "0.1, 0.2"
julia = "1.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
PerformanceTestTools = "dc46b164-d16f-48ec-a853-60448fc869fe"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Aqua", "CategoricalArrays", "DataFrames", "Documenter", "InteractiveUtils", "PerformanceTestTools", "Pkg", "StaticArrays", "StructArrays", "Test", "TypedTables", "Zygote"]
